### ISSUE TITLE
No such file or directory: 'list.rd.txt'

### ISSUE THREAD

**Issue by villa9393** [snavely/bundler_sfm#64]
Hi ,

i encounter another error as below

Performing Bundler2PMVS conversion...
Error opening file list.txt for reading
Error opening file pmvs/bundle.rd.out for reading
Num cameras: 0
Running Bundle2PMVS to generate geometry and converted camera file
Running RadialUndistort to undistort input images
Running Bundle2Vis to generate vis.dat
Traceback (most recent call last):
File "RunPMVS.py", line 10, in
manager.doBundle2PMVS()
File "c:\Users\villa\Desktop\osm-bundler\osm-bundlerWin64\osmpmvs_init_.py", line 86, in doBundle2PMVS
undistortTextFile = open("list.rd.txt", "r")
IOError: [Errno 2] No such file or directory: 'list.rd.txt'

Any idea how to solve it?

Many thanks in advance

**Comment by snavely** [comment]
Hi -- are you still experiencing this issue?
